all:
	gcc -m32 -o alarm       alarm.c
	gcc -m32 -o fork        fork.c
	gcc -m32 -o itimer      itimer.c
	gcc -m32 -o kill        kill.c
	gcc -m32 -o proc        proc.c
	gcc -m32 -o sigprocmask sigprocmask.c
	gcc -m32 -o sigset      sigset.c
	gcc -m32 -o sleep       sleep.c
	gcc -m32 -o vfork       vfork.c

clean:
	rm -rf  alarm       \
		fork        \
		itimer      \
		kill        \
		proc        \
		sigprocmask \
		sigset      \
		sleep       \
		vfork       \
