all:
	gcc -m32 -o msga     msga.c
	gcc -m32 -o msgb     msgb.c
	gcc -m32 -o msgtypea msgtypea.c
	gcc -m32 -o msgtypeb msgtypeb.c
	gcc -m32 -o pipea    pipea.c
	gcc -m32 -o pipeb    pipeb.c
	gcc -m32 -o shma     shma.c
	gcc -m32 -o shmb     shmb.c
	gcc -m32 -o shmctl   shmctl.c

clean:
	rm -rf  msga     \
		msgb     \
		msgtypea \
		msgtypeb \
		pipea    \
		pipeb    \
		shma     \
		shmb     \
		shmctl   
