all:
	gcc -m32 -o csem   csem.c
	gcc -m32 -o gsem   gsem.c
	gcc -m32 -o netcli netcli.c
	gcc -m32 -o netsvr netsvr.c
	gcc -m32 -o tcpsvr tcpsvr.c

clean:
	rm -rf  csem   \
		gsem   \
		netcli \
		netsvr \
		tcpsvr 
