all:
	gcc -m32 -o child   child.c    
	gcc -m32 -o execl   execl.c
	gcc -m32 -o exit    exit.c
	gcc -m32 -o father  father.c
	gcc -m32 -o signal  signal.c
	gcc -m32 -o vfork   vfork.c
	gcc -m32 -o wait    wait.c
	gcc -m32 -o waitpid waitpid.c
clean:
	rm -rf child   \
		execl  \
		exit   \
		father \
		signal \
		vfork  \
		wait   \
		waitpid 
