all:
	gcc -m32 -o fork    fork.c
	gcc -m32 -o ftab    ftab.c
	gcc -m32 -o id      id.c
	gcc -m32 -o is      is.c
	gcc -m32 -o list    list.c
	gcc -m32 -o mem     mem.c
	gcc -m32 -o orphan  orphan.c
	gcc -m32 -o os      os.c
	gcc -m32 -o pid     pid.c
	gcc -m32 -o tree    tree.c
	gcc -m32 -o zombie  zombie.c

clean:
	rm fork ftab id is list mem orphan os pid tree zombie  

